services:
#  web:
#    build: .
#    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
#    volumes:
#      - ./project:/app
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    environment:
#      - DATABASE_NAME=HalalDamu
#      - DATABASE_USER=postgres
#      - DATABASE_PASSWORD=postgres
#      - DATABASE_HOST=localhost
#      - DATABASE_PORT=5432

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
